import { db } from "../src/lib/db";
import { calendarTemplates } from "../src/lib/db/schema";

const templates = [
  {
    id: "classic-white",
    name: "Classic White",
    description: "Clean white background with thin grid lines and elegant serif titles",
    category: "classic",
    isPremium: false,
    sortOrder: 1,
    config: {
      orientation: "portrait",
      supportedSizes: ["A4", "A5"],
      coverLayout: {
        imageArea: { x: 10, y: 10, width: 80, height: 60 },
        titleArea: { x: 10, y: 72, width: 80, height: 10 },
        yearArea: { x: 10, y: 84, width: 80, height: 8 },
      },
      monthLayout: {
        imageArea: { x: 5, y: 5, width: 90, height: 50 },
        calendarGridArea: { x: 5, y: 58, width: 90, height: 37 },
        monthTitleArea: { x: 5, y: 55, width: 90, height: 5 },
      },
      typography: {
        monthTitleFont: "Georgia",
        monthTitleSize: 24,
        dayFont: "Georgia",
        daySize: 11,
        yearFont: "Georgia",
        yearSize: 36,
      },
      colors: {
        background: "#FFFFFF",
        text: "#1A1A1A",
        accent: "#8B4513",
        gridLines: "#E5E5E5",
        weekendHighlight: "#FFF5F0",
      },
      grid: { showWeekNumbers: false, firstDayOfWeek: 1, dayHeaderFormat: "short" },
      bleed: 3,
      dpi: 300,
    },
  },
  {
    id: "modern-dark",
    name: "Modern Dark",
    description: "Dark background with bold sans-serif typography and high contrast",
    category: "modern",
    isPremium: false,
    sortOrder: 2,
    config: {
      orientation: "portrait",
      supportedSizes: ["A4", "A5"],
      coverLayout: {
        imageArea: { x: 5, y: 5, width: 90, height: 65 },
        titleArea: { x: 5, y: 72, width: 90, height: 10 },
        yearArea: { x: 5, y: 84, width: 90, height: 8 },
      },
      monthLayout: {
        imageArea: { x: 3, y: 3, width: 94, height: 52 },
        calendarGridArea: { x: 5, y: 58, width: 90, height: 37 },
        monthTitleArea: { x: 5, y: 55, width: 90, height: 5 },
      },
      typography: {
        monthTitleFont: "Helvetica",
        monthTitleSize: 28,
        dayFont: "Helvetica",
        daySize: 11,
        yearFont: "Helvetica",
        yearSize: 42,
      },
      colors: {
        background: "#1A1A2E",
        text: "#FFFFFF",
        accent: "#E94560",
        gridLines: "#2A2A4A",
        weekendHighlight: "#1F1F3A",
      },
      grid: { showWeekNumbers: false, firstDayOfWeek: 1, dayHeaderFormat: "short" },
      bleed: 3,
      dpi: 300,
    },
  },
  {
    id: "minimal-grid",
    name: "Minimal Grid",
    description: "Ultra minimalist design with hairline grid and generous whitespace",
    category: "minimal",
    isPremium: false,
    sortOrder: 3,
    config: {
      orientation: "portrait",
      supportedSizes: ["A4", "A5"],
      coverLayout: {
        imageArea: { x: 15, y: 15, width: 70, height: 50 },
        titleArea: { x: 15, y: 68, width: 70, height: 8 },
        yearArea: { x: 15, y: 78, width: 70, height: 8 },
      },
      monthLayout: {
        imageArea: { x: 10, y: 8, width: 80, height: 48 },
        calendarGridArea: { x: 10, y: 60, width: 80, height: 32 },
        monthTitleArea: { x: 10, y: 56, width: 80, height: 5 },
      },
      typography: {
        monthTitleFont: "Helvetica Neue",
        monthTitleSize: 18,
        dayFont: "Helvetica Neue",
        daySize: 10,
        yearFont: "Helvetica Neue",
        yearSize: 32,
      },
      colors: {
        background: "#FAFAFA",
        text: "#333333",
        accent: "#999999",
        gridLines: "#F0F0F0",
        weekendHighlight: "#F5F5F5",
      },
      grid: { showWeekNumbers: false, firstDayOfWeek: 1, dayHeaderFormat: "narrow" },
      bleed: 3,
      dpi: 300,
    },
  },
  {
    id: "watercolor",
    name: "Watercolor",
    description: "Soft pastel watercolor backgrounds that rotate by month",
    category: "artistic",
    isPremium: false,
    sortOrder: 4,
    config: {
      orientation: "portrait",
      supportedSizes: ["A4", "A5"],
      coverLayout: {
        imageArea: { x: 10, y: 10, width: 80, height: 55 },
        titleArea: { x: 10, y: 68, width: 80, height: 10 },
        yearArea: { x: 10, y: 80, width: 80, height: 8 },
      },
      monthLayout: {
        imageArea: { x: 8, y: 6, width: 84, height: 50 },
        calendarGridArea: { x: 8, y: 60, width: 84, height: 34 },
        monthTitleArea: { x: 8, y: 56, width: 84, height: 5 },
      },
      typography: {
        monthTitleFont: "Georgia",
        monthTitleSize: 22,
        dayFont: "Georgia",
        daySize: 11,
        yearFont: "Georgia",
        yearSize: 34,
      },
      colors: {
        background: "#FDF6F0",
        text: "#5C4033",
        accent: "#D4A574",
        gridLines: "#E8DDD4",
        weekendHighlight: "#FFF8F2",
      },
      grid: { showWeekNumbers: false, firstDayOfWeek: 1, dayHeaderFormat: "short" },
      bleed: 3,
      dpi: 300,
    },
  },
  {
    id: "bold-color",
    name: "Bold Color",
    description: "Vibrant solid colours that rotate through a bold palette",
    category: "modern",
    isPremium: false,
    sortOrder: 5,
    config: {
      orientation: "portrait",
      supportedSizes: ["A4", "A5"],
      coverLayout: {
        imageArea: { x: 8, y: 8, width: 84, height: 58 },
        titleArea: { x: 8, y: 70, width: 84, height: 10 },
        yearArea: { x: 8, y: 82, width: 84, height: 8 },
      },
      monthLayout: {
        imageArea: { x: 5, y: 5, width: 90, height: 50 },
        calendarGridArea: { x: 5, y: 58, width: 90, height: 37 },
        monthTitleArea: { x: 5, y: 55, width: 90, height: 5 },
      },
      typography: {
        monthTitleFont: "Futura",
        monthTitleSize: 26,
        dayFont: "Futura",
        daySize: 11,
        yearFont: "Futura",
        yearSize: 40,
      },
      colors: {
        background: "#FF6B35",
        text: "#FFFFFF",
        accent: "#FFFFFF",
        gridLines: "rgba(255,255,255,0.3)",
        weekendHighlight: "rgba(255,255,255,0.1)",
      },
      grid: { showWeekNumbers: false, firstDayOfWeek: 1, dayHeaderFormat: "short" },
      bleed: 3,
      dpi: 300,
    },
  },
  {
    id: "monochrome",
    name: "Monochrome",
    description: "Black and white design with strong typography",
    category: "minimal",
    isPremium: false,
    sortOrder: 6,
    config: {
      orientation: "portrait",
      supportedSizes: ["A4", "A5"],
      coverLayout: {
        imageArea: { x: 5, y: 5, width: 90, height: 60 },
        titleArea: { x: 5, y: 68, width: 90, height: 12 },
        yearArea: { x: 5, y: 82, width: 90, height: 10 },
      },
      monthLayout: {
        imageArea: { x: 5, y: 3, width: 90, height: 52 },
        calendarGridArea: { x: 5, y: 58, width: 90, height: 37 },
        monthTitleArea: { x: 5, y: 55, width: 90, height: 5 },
      },
      typography: {
        monthTitleFont: "Impact",
        monthTitleSize: 30,
        dayFont: "Helvetica",
        daySize: 11,
        yearFont: "Impact",
        yearSize: 48,
      },
      colors: {
        background: "#FFFFFF",
        text: "#000000",
        accent: "#000000",
        gridLines: "#CCCCCC",
        weekendHighlight: "#F5F5F5",
      },
      grid: { showWeekNumbers: false, firstDayOfWeek: 1, dayHeaderFormat: "short" },
      bleed: 3,
      dpi: 300,
    },
  },
  {
    id: "vintage",
    name: "Vintage",
    description: "Sepia tones with decorative borders and elegant script fonts",
    category: "classic",
    isPremium: false,
    sortOrder: 7,
    config: {
      orientation: "portrait",
      supportedSizes: ["A4", "A5"],
      coverLayout: {
        imageArea: { x: 12, y: 12, width: 76, height: 52 },
        titleArea: { x: 12, y: 68, width: 76, height: 10 },
        yearArea: { x: 12, y: 80, width: 76, height: 8 },
      },
      monthLayout: {
        imageArea: { x: 10, y: 8, width: 80, height: 48 },
        calendarGridArea: { x: 8, y: 60, width: 84, height: 34 },
        monthTitleArea: { x: 8, y: 56, width: 84, height: 5 },
      },
      typography: {
        monthTitleFont: "Palatino",
        monthTitleSize: 24,
        dayFont: "Palatino",
        daySize: 11,
        yearFont: "Palatino",
        yearSize: 36,
      },
      colors: {
        background: "#F5ECD7",
        text: "#4A3728",
        accent: "#8B6914",
        gridLines: "#D4C5A9",
        weekendHighlight: "#F0E6CC",
      },
      grid: { showWeekNumbers: false, firstDayOfWeek: 1, dayHeaderFormat: "short" },
      bleed: 3,
      dpi: 300,
    },
  },
  {
    id: "nature",
    name: "Nature",
    description: "Earth tones with organic decorative elements",
    category: "artistic",
    isPremium: false,
    sortOrder: 8,
    config: {
      orientation: "portrait",
      supportedSizes: ["A4", "A5"],
      coverLayout: {
        imageArea: { x: 8, y: 8, width: 84, height: 58 },
        titleArea: { x: 8, y: 70, width: 84, height: 10 },
        yearArea: { x: 8, y: 82, width: 84, height: 8 },
      },
      monthLayout: {
        imageArea: { x: 5, y: 5, width: 90, height: 50 },
        calendarGridArea: { x: 5, y: 58, width: 90, height: 37 },
        monthTitleArea: { x: 5, y: 55, width: 90, height: 5 },
      },
      typography: {
        monthTitleFont: "Garamond",
        monthTitleSize: 22,
        dayFont: "Garamond",
        daySize: 11,
        yearFont: "Garamond",
        yearSize: 34,
      },
      colors: {
        background: "#F0EBE3",
        text: "#2D4A22",
        accent: "#6B8F4E",
        gridLines: "#D4CCBC",
        weekendHighlight: "#E8E2D8",
      },
      grid: { showWeekNumbers: false, firstDayOfWeek: 1, dayHeaderFormat: "short" },
      bleed: 3,
      dpi: 300,
    },
  },
  {
    id: "geometric",
    name: "Geometric",
    description: "Clean geometric pattern backgrounds with modern feel",
    category: "modern",
    isPremium: false,
    sortOrder: 9,
    config: {
      orientation: "portrait",
      supportedSizes: ["A4", "A5"],
      coverLayout: {
        imageArea: { x: 10, y: 10, width: 80, height: 55 },
        titleArea: { x: 10, y: 68, width: 80, height: 10 },
        yearArea: { x: 10, y: 80, width: 80, height: 8 },
      },
      monthLayout: {
        imageArea: { x: 5, y: 5, width: 90, height: 50 },
        calendarGridArea: { x: 5, y: 58, width: 90, height: 37 },
        monthTitleArea: { x: 5, y: 55, width: 90, height: 5 },
      },
      typography: {
        monthTitleFont: "Avenir",
        monthTitleSize: 22,
        dayFont: "Avenir",
        daySize: 11,
        yearFont: "Avenir",
        yearSize: 36,
      },
      colors: {
        background: "#F8F9FA",
        text: "#2C3E50",
        accent: "#3498DB",
        gridLines: "#DEE2E6",
        weekendHighlight: "#EBF5FB",
      },
      grid: { showWeekNumbers: false, firstDayOfWeek: 1, dayHeaderFormat: "short" },
      bleed: 3,
      dpi: 300,
    },
  },
  {
    id: "photo-full",
    name: "Full Photo",
    description: "Image bleeds to the edge with calendar overlay on the photo",
    category: "modern",
    isPremium: false,
    sortOrder: 10,
    config: {
      orientation: "portrait",
      supportedSizes: ["A4", "A5"],
      coverLayout: {
        imageArea: { x: 0, y: 0, width: 100, height: 100 },
        titleArea: { x: 10, y: 70, width: 80, height: 10 },
        yearArea: { x: 10, y: 82, width: 80, height: 8 },
      },
      monthLayout: {
        imageArea: { x: 0, y: 0, width: 100, height: 100 },
        calendarGridArea: { x: 5, y: 60, width: 90, height: 35 },
        monthTitleArea: { x: 5, y: 55, width: 90, height: 5 },
      },
      typography: {
        monthTitleFont: "Helvetica",
        monthTitleSize: 22,
        dayFont: "Helvetica",
        daySize: 10,
        yearFont: "Helvetica",
        yearSize: 36,
      },
      colors: {
        background: "#000000",
        text: "#FFFFFF",
        accent: "#FFFFFF",
        gridLines: "rgba(255,255,255,0.3)",
        weekendHighlight: "rgba(255,255,255,0.1)",
      },
      grid: { showWeekNumbers: false, firstDayOfWeek: 1, dayHeaderFormat: "short" },
      bleed: 3,
      dpi: 300,
    },
  },
  {
    id: "split-view",
    name: "Split View",
    description: "50/50 image and calendar side by side in landscape orientation",
    category: "classic",
    isPremium: false,
    sortOrder: 11,
    config: {
      orientation: "landscape",
      supportedSizes: ["A4", "A5"],
      coverLayout: {
        imageArea: { x: 0, y: 0, width: 50, height: 100 },
        titleArea: { x: 55, y: 30, width: 40, height: 15 },
        yearArea: { x: 55, y: 50, width: 40, height: 10 },
      },
      monthLayout: {
        imageArea: { x: 0, y: 0, width: 50, height: 100 },
        calendarGridArea: { x: 55, y: 20, width: 40, height: 70 },
        monthTitleArea: { x: 55, y: 8, width: 40, height: 10 },
      },
      typography: {
        monthTitleFont: "Georgia",
        monthTitleSize: 24,
        dayFont: "Georgia",
        daySize: 11,
        yearFont: "Georgia",
        yearSize: 36,
      },
      colors: {
        background: "#FFFFFF",
        text: "#1A1A1A",
        accent: "#4A90D9",
        gridLines: "#E5E5E5",
        weekendHighlight: "#F5F8FC",
      },
      grid: { showWeekNumbers: false, firstDayOfWeek: 1, dayHeaderFormat: "short" },
      bleed: 3,
      dpi: 300,
    },
  },
  {
    id: "magazine",
    name: "Magazine",
    description: "Editorial style layout with large image and compact calendar",
    category: "modern",
    isPremium: false,
    sortOrder: 12,
    config: {
      orientation: "portrait",
      supportedSizes: ["A4", "A5"],
      coverLayout: {
        imageArea: { x: 5, y: 3, width: 90, height: 70 },
        titleArea: { x: 5, y: 76, width: 90, height: 8 },
        yearArea: { x: 5, y: 86, width: 90, height: 6 },
      },
      monthLayout: {
        imageArea: { x: 3, y: 3, width: 94, height: 60 },
        calendarGridArea: { x: 5, y: 68, width: 90, height: 28 },
        monthTitleArea: { x: 5, y: 64, width: 90, height: 5 },
      },
      typography: {
        monthTitleFont: "Didot",
        monthTitleSize: 20,
        dayFont: "Helvetica Neue",
        daySize: 9,
        yearFont: "Didot",
        yearSize: 30,
      },
      colors: {
        background: "#FFFFFF",
        text: "#1A1A1A",
        accent: "#C62828",
        gridLines: "#E0E0E0",
        weekendHighlight: "#FFF5F5",
      },
      grid: { showWeekNumbers: false, firstDayOfWeek: 1, dayHeaderFormat: "narrow" },
      bleed: 3,
      dpi: 300,
    },
  },
  {
    id: "kids",
    name: "Kids",
    description: "Playful design with rounded fonts and bright colours — perfect for children",
    category: "artistic",
    isPremium: true,
    sortOrder: 13,
    config: {
      orientation: "portrait",
      supportedSizes: ["A4", "A5"],
      coverLayout: {
        imageArea: { x: 8, y: 8, width: 84, height: 55 },
        titleArea: { x: 8, y: 66, width: 84, height: 12 },
        yearArea: { x: 8, y: 80, width: 84, height: 10 },
      },
      monthLayout: {
        imageArea: { x: 5, y: 5, width: 90, height: 48 },
        calendarGridArea: { x: 5, y: 58, width: 90, height: 37 },
        monthTitleArea: { x: 5, y: 53, width: 90, height: 6 },
      },
      typography: {
        monthTitleFont: "Comic Sans MS",
        monthTitleSize: 26,
        dayFont: "Comic Sans MS",
        daySize: 12,
        yearFont: "Comic Sans MS",
        yearSize: 38,
      },
      colors: {
        background: "#FFF9C4",
        text: "#4A148C",
        accent: "#E91E63",
        gridLines: "#CE93D8",
        weekendHighlight: "#F3E5F5",
      },
      grid: { showWeekNumbers: false, firstDayOfWeek: 1, dayHeaderFormat: "short" },
      bleed: 3,
      dpi: 300,
    },
  },
];

async function seedTemplates() {
  console.log("Seeding calendar templates...");

  for (const template of templates) {
    await db
      .insert(calendarTemplates)
      .values(template)
      .onConflictDoUpdate({
        target: calendarTemplates.id,
        set: {
          name: template.name,
          description: template.description,
          category: template.category,
          config: template.config,
          isPremium: template.isPremium,
          sortOrder: template.sortOrder,
        },
      });
    console.log(`  Seeded: ${template.id}`);
  }

  console.log(`Done. ${templates.length} templates seeded.`);
  process.exit(0);
}

seedTemplates().catch((err) => {
  console.error("Failed to seed templates:", err);
  process.exit(1);
});
